import type { GeneratedFile, LoopSpec, ProjectScan } from "../core/types.js";

export function generateAgentsFiles(scan: ProjectScan, loops: LoopSpec[]): GeneratedFile[] {
  return [
    {
      path: "AGENTS.md",
      content: renderAgents(scan, loops)
    }
  ];
}

function renderAgents(scan: ProjectScan, loops: LoopSpec[]) {
  const commands =
    [
      scan.commands.install ? `- Install: \`${scan.commands.install}\`` : undefined,
      scan.commands.test ? `- Test: \`${scan.commands.test}\`` : undefined,
      scan.commands.lint ? `- Lint: \`${scan.commands.lint}\`` : undefined,
      scan.commands.build ? `- Build: \`${scan.commands.build}\`` : undefined,
      scan.commands.format ? `- Format: \`${scan.commands.format}\`` : undefined
    ]
      .filter(Boolean)
      .join("\n") || "- No verification commands were inferred. Add them before running a loop.";

  const loopSections = loops.map((loop) => renderLoopSection(loop)).join("\n\n");

  return `# AGENTS.md

Generated by [loopgen](https://www.npmjs.com/package/loopgen) for ${scan.projectName}. This file is read by
many AI coding agents (Claude Code, Codex, Cursor, GitHub Copilot, Gemini CLI, Aider, and others). It
describes bounded, verifiable loops with safety rails: keep changes small, run verification, and stop at
the iteration limit.

## Project

- Primary language: ${scan.primaryLanguage}
- Package managers: ${scan.packageManagers.join(", ") || "none detected"}

### Verification commands

${commands}

## Safety rules for every loop

- Make the smallest change that can satisfy the goal.
- Run the verification commands before declaring success; never declare success without output.
- Keep maker and checker work separate: propose, verify, then review the diff and command output.
- Do not read or modify secret or credential files (see each loop's forbidden paths).
- Append an attempt log to the loop's state file after every iteration.
- Stop and ask a human when a stop condition is met instead of guessing.

## Loops

${loopSections}
`;
}

function renderLoopSection(loop: LoopSpec) {
  return `### ${loop.title} (\`${loop.id}\`)

${loop.goal}

- Category: ${loop.category}
- Trigger: ${loop.trigger.type} (${loop.trigger.cadence})
- Max iterations: ${loop.stopCriteria.maxIterations}
- State file: \`${loop.stateFile}\`

Context to gather:
${loop.contextSources.map((source) => `- ${source}`).join("\n")}

Steps:
${loop.actions.map((action, index) => `${index + 1}. ${action}`).join("\n")}

Verify:
${loop.verification.commands.map((command) => `- \`${command}\``).join("\n")}

Acceptance criteria: ${loop.verification.acceptanceCriteria}

Do not read or modify: ${loop.permissions.forbiddenPaths.map((item) => `\`${item}\``).join(", ")}

Stop and ask for human input when:
${loop.stopCriteria.requireHumanInputOn.map((condition) => `- ${condition}`).join("\n")}${
    loop.verification.requiresHumanCommandDefinition
      ? "\n\n> This loop is a draft until the TODO verification command is replaced."
      : ""
  }`;
}
