import type { GeneratedFile, LoopSpec, ProjectScan } from "../core/types.js";

export function generateCursorFiles(scan: ProjectScan, loops: LoopSpec[]): GeneratedFile[] {
  return loops.map((loop) => ({
    path: `.cursor/rules/loopgen-${loop.id}.mdc`,
    content: cursorRule(scan, loop)
  }));
}

function cursorRule(scan: ProjectScan, loop: LoopSpec) {
  return `---
description: ${loop.goal}
globs:
alwaysApply: false
---

# ${loop.title}

Bounded loop-engineering rule for ${scan.projectName}, generated by loopgen. Apply this rule when working
on \`${loop.id}\`.

## Goal

${loop.goal}

## Steps

${loop.actions.map((action, index) => `${index + 1}. ${action}`).join("\n")}

## Verify before declaring success

${loop.verification.commands.map((command) => `- \`${command}\``).join("\n")}

Acceptance criteria: ${loop.verification.acceptanceCriteria}

## Guardrails

- Maximum iterations: ${loop.stopCriteria.maxIterations}.
- Keep maker and checker work separate.
- Do not read or modify: ${loop.permissions.forbiddenPaths.map((item) => `\`${item}\``).join(", ")}.
- Log every attempt to \`${loop.stateFile}\`.
- Stop and ask for human input when: ${loop.stopCriteria.requireHumanInputOn.join("; ")}.
${loop.verification.requiresHumanCommandDefinition ? "\nThis rule is a draft until the TODO verification command is replaced.\n" : ""}`;
}
