import type { GeneratedFile, LoopSpec, ProjectScan } from "../core/types.js";

export function generateWindsurfFiles(scan: ProjectScan, loops: LoopSpec[]): GeneratedFile[] {
  return [
    {
      path: ".windsurfrules",
      content: renderWindsurfRules(scan, loops)
    }
  ];
}

function renderWindsurfRules(scan: ProjectScan, loops: LoopSpec[]) {
  const loopSections = loops.map((loop) => renderLoopSection(loop)).join("\n\n");
  return `# loopgen rules for ${scan.projectName}

Generated by loopgen. These are bounded, verifiable loops with safety rails for Windsurf/Cascade. Keep
changes small, run verification, and stop at the iteration limit.

## Global guardrails

- Make the smallest change that satisfies the goal.
- Run verification commands before declaring success.
- Keep maker and checker work separate.
- Never read or modify secret or credential files.
- Log every attempt to the loop's state file and stop when a stop condition is met.

${loopSections}
`;
}

function renderLoopSection(loop: LoopSpec) {
  return `## ${loop.title} (${loop.id})

${loop.goal}

Steps:
${loop.actions.map((action, index) => `${index + 1}. ${action}`).join("\n")}

Verify:
${loop.verification.commands.map((command) => `- \`${command}\``).join("\n")}

Guardrails: max ${loop.stopCriteria.maxIterations} iterations; state file \`${loop.stateFile}\`; do not touch ${loop.permissions.forbiddenPaths
    .map((item) => `\`${item}\``)
    .join(", ")}.${loop.verification.requiresHumanCommandDefinition ? " Draft until a real verification command is set." : ""}`;
}
