import { stringify } from "yaml";
import { generateClaudeFiles } from "../adapters/claude.js";
import { generateCodexFiles } from "../adapters/codex.js";
import { createPreviewDiff } from "./diff.js";
import { defaultAnswers, createLoopSpec } from "./templates.js";
import { scanProject } from "./scanner.js";
import type { AdapterId, GeneratedFile, GenerationOptions, GenerationResult, LoopTemplateId } from "./types.js";

const DEFAULT_TEMPLATES: LoopTemplateId[] = [
  "ci-failure-repair",
  "test-repair",
  "dependency-upgrade",
  "pr-comment-handling"
];

export async function generateLoopProject(options: GenerationOptions): Promise<GenerationResult> {
  const scan = await scanProject(options.projectRoot);
  const adapters = options.adapters?.length ? unique(options.adapters) : (["codex", "claude"] as AdapterId[]);
  const selectedTemplates = options.selectedTemplates?.length ? unique(options.selectedTemplates) : DEFAULT_TEMPLATES;
  const answers = defaultAnswers(scan, {
    adapters,
    selectedTemplates,
    triggerCadence: options.triggerCadence ?? "manual",
    acceptanceCriteria: options.acceptanceCriteria,
    allowPrCreation: options.allowPrCreation ?? false,
    allowedCommands: options.allowedCommands?.length ? options.allowedCommands : undefined,
    maxIterations: options.maxIterations ?? 3
  });

  const loops = answers.selectedTemplates.map((id) => createLoopSpec(id, scan, answers));
  const files = sortFiles([
    {
      path: ".loopgen/loopgen.loop.yaml",
      content: renderLoopYaml(scan.projectName, loops)
    },
    {
      path: ".loopgen/README.md",
      content: renderLoopgenReadme(scan.projectName)
    },
    ...loops.map((loop) => ({
      path: loop.stateFile,
      content: renderStateFile(loop.id, loop.title)
    })),
    ...(answers.adapters.includes("codex") ? generateCodexFiles(scan, loops) : []),
    ...(answers.adapters.includes("claude") ? generateClaudeFiles(scan, loops) : [])
  ]);

  const warnings = [
    ...scan.warnings,
    ...loops
      .filter((loop) => loop.verification.requiresHumanCommandDefinition)
      .map((loop) => `${loop.id} needs a real verification command before automated execution.`)
  ];

  return {
    scan,
    loops,
    files,
    diff: await createPreviewDiff(scan.root, files),
    warnings
  };
}

function renderLoopYaml(projectName: string, loops: unknown[]) {
  return stringify(
    {
      version: "0.1",
      project: projectName,
      generatedBy: "loopgen",
      generatedAt: new Date().toISOString(),
      loops
    },
    { lineWidth: 110 }
  );
}

function renderLoopgenReadme(projectName: string) {
  return `# loopgen for ${projectName}

This directory contains local-first loop engineering configuration generated by loopgen.

Start with \`.loopgen/loopgen.loop.yaml\`, then use the generated Codex or Claude skill that matches the loop you want to run.

Safety defaults:

- Preview diffs before applying changes.
- Keep maker and checker work separate.
- Stop after the configured maximum iterations.
- Do not read production secrets or forbidden paths.
- Do not declare success without verification output.
`;
}

function renderStateFile(id: string, title: string) {
  return `# ${title} state

Loop id: ${id}

## Attempts

- No attempts yet.
`;
}

function sortFiles(files: GeneratedFile[]) {
  return files.sort((a, b) => a.path.localeCompare(b.path));
}

function unique<T>(items: T[]) {
  return [...new Set(items)];
}
