import path from "node:path";
import { fileURLToPath } from "node:url";
import { stringify } from "yaml";
import { generateClaudeFiles } from "../adapters/claude.js";
import { generateCodexFiles } from "../adapters/codex.js";
import { createPreviewDiff } from "./diff.js";
import { defaultAnswers, createLoopSpec, TEMPLATE_DEFINITIONS, templateIds } from "./templates.js";
import { scanProject } from "./scanner.js";
import type { AdapterId, ExperienceMode, GeneratedFile, GenerationOptions, GenerationResult, LoopSpec, LoopTemplateId, TemplateDefinition } from "./types.js";

export async function generateLoopProject(options: GenerationOptions): Promise<GenerationResult> {
  const experienceMode = options.experienceMode ?? "project";
  const projectRoot = resolveProjectRoot(options, experienceMode);
  const scan = await scanProject(projectRoot);
  const adapters = options.adapters?.length ? unique(options.adapters) : (["codex", "claude"] as AdapterId[]);
  const selectedTemplates = options.selectedTemplates?.length
    ? unique(options.selectedTemplates)
    : defaultTemplateSelection(options, experienceMode);
  const answers = defaultAnswers(scan, {
    adapters,
    selectedTemplates,
    triggerCadence: options.triggerCadence ?? "manual",
    acceptanceCriteria: options.acceptanceCriteria,
    allowPrCreation: options.allowPrCreation ?? false,
    allowedCommands: options.allowedCommands?.length ? options.allowedCommands : undefined,
    maxIterations: options.maxIterations ?? 3
  });

  const loops = answers.selectedTemplates.map((id) => createLoopSpec(id, scan, answers));
  const files = sortFiles([
    {
      path: ".loopgen/loopgen.loop.yaml",
      content: renderLoopYaml(scan.projectName, loops)
    },
    {
      path: ".loopgen/README.md",
      content: renderLoopgenReadme(scan.projectName)
    },
    ...loops.map((loop) => ({
      path: `.loopgen/playbooks/${loop.id}.md`,
      content: renderPlaybook(scan.projectName, loop)
    })),
    ...loops.map((loop) => ({
      path: loop.stateFile,
      content: renderStateFile(loop.id, loop.title)
    })),
    ...(answers.adapters.includes("codex") ? generateCodexFiles(scan, loops) : []),
    ...(answers.adapters.includes("claude") ? generateClaudeFiles(scan, loops) : [])
  ]);

  const warnings = [
    ...scan.warnings,
    ...loops
      .filter((loop) => loop.verification.requiresHumanCommandDefinition)
      .map((loop) => `${loop.id} needs a real verification command before automated execution.`)
  ];

  return {
    experienceMode,
    scan,
    loops,
    files,
    diff: await createPreviewDiff(scan.root, files),
    warnings
  };
}

export function demoProjectRoot() {
  const currentDir = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(currentDir, "..", "..", "examples", "demo-webapp");
}

function resolveProjectRoot(options: GenerationOptions, experienceMode: ExperienceMode) {
  if (experienceMode === "demo") {
    return demoProjectRoot();
  }
  return path.resolve(options.projectRoot ?? ".");
}

function defaultTemplateSelection(options: GenerationOptions, experienceMode: ExperienceMode): LoopTemplateId[] {
  const templates = filterTemplateDefinitions(options);
  if (experienceMode === "demo") {
    const demoRecommended = templates.filter((template) => template.demoAvailable && template.recommendedForDemo);
    if (demoRecommended.length > 0) return demoRecommended.map((template) => template.id);
    return templates.filter((template) => template.demoAvailable).map((template) => template.id);
  }
  return templates.length ? templates.map((template) => template.id) : templateIds();
}

function filterTemplateDefinitions(options: GenerationOptions): TemplateDefinition[] {
  return TEMPLATE_DEFINITIONS.filter((template) => {
    const audienceMatches = !options.audienceFilter || template.audience.includes(options.audienceFilter);
    const categoryMatches = !options.categoryFilter || template.category === options.categoryFilter;
    return audienceMatches && categoryMatches;
  });
}

function renderLoopYaml(projectName: string, loops: unknown[]) {
  return stringify(
    {
      version: "0.1",
      project: projectName,
      generatedBy: "loopgen",
      generatedAt: new Date().toISOString(),
      loops
    },
    { lineWidth: 110 }
  );
}

function renderLoopgenReadme(projectName: string) {
  return `# loopgen for ${projectName}

This directory contains local-first loop engineering configuration generated by loopgen.

Start with \`.loopgen/loopgen.loop.yaml\`, then read the matching \`.loopgen/playbooks/*.md\` file.
If you use Codex or Claude, use the generated skill or loop guide that matches the same loop id.

Safety defaults:

- Preview diffs before applying changes.
- Keep maker and checker work separate.
- Stop after the configured maximum iterations.
- Do not read production secrets or forbidden paths.
- Do not declare success without verification output.
`;
}

function renderPlaybook(projectName: string, loop: LoopSpec) {
  return `# ${loop.title} playbook

Project: ${projectName}
Loop id: ${loop.id}
Category: ${loop.category}
Audience: ${loop.audience.join(", ")}
Difficulty: ${loop.difficulty}

## Goal

${loop.goal}

Expected outcome: ${loop.expectedOutcome}

## When to run

- Trigger type: ${loop.trigger.type}
- Cadence: ${loop.trigger.cadence}
- Sources: ${loop.trigger.sources.join(", ")}

## Context to gather

${loop.contextSources.map((source) => `- ${source}`).join("\n")}

## Loop steps

${loop.actions.map((action, index) => `${index + 1}. ${action}`).join("\n")}

## Verification

Run these commands before declaring success:

${loop.verification.commands.map((command) => `- \`${command}\``).join("\n")}

Acceptance criteria: ${loop.verification.acceptanceCriteria}

## Safety and state

- State file: \`${loop.stateFile}\`
- Maximum iterations: ${loop.stopCriteria.maxIterations}
- Timeout minutes: ${loop.stopCriteria.timeoutMinutes}
- Maker/checker separation required: ${loop.verification.makerChecker ? "yes" : "no"}
- Network allowed: ${loop.permissions.allowNetwork ? "yes" : "no"}
- PR creation allowed: ${loop.permissions.allowPrCreation ? "yes" : "no"}
- Do not read or modify: ${loop.permissions.forbiddenPaths.map((item) => `\`${item}\``).join(", ")}

Stop and ask for human input when:

${loop.stopCriteria.requireHumanInputOn.map((condition) => `- ${condition}`).join("\n")}
${loop.verification.requiresHumanCommandDefinition ? "\nThis playbook is in draft mode until the TODO verification command is replaced.\n" : ""}
`;
}

function renderStateFile(id: string, title: string) {
  return `# ${title} state

Loop id: ${id}

## Attempts

- No attempts yet.
`;
}

function sortFiles(files: GeneratedFile[]) {
  return files.sort((a, b) => fileSortKey(a.path).localeCompare(fileSortKey(b.path)));
}

function fileSortKey(filePath: string) {
  if (filePath.startsWith(".loopgen/playbooks/")) return `0:${filePath}`;
  if (filePath === ".loopgen/README.md") return `1:${filePath}`;
  if (filePath === ".loopgen/loopgen.loop.yaml") return `2:${filePath}`;
  if (filePath.startsWith(".loopgen/state/")) return `3:${filePath}`;
  if (filePath.startsWith(".codex/")) return `4:${filePath}`;
  if (filePath.startsWith(".claude/")) return `5:${filePath}`;
  return `6:${filePath}`;
}

function unique<T>(items: T[]) {
  return [...new Set(items)];
}
